name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Post checkout repo step
    - name: Post checkout repo
      run: echo "Actions completed successfully."

    # Build Docker image
    - name: Build Docker image
      run: |
        cd Python/api  # Navigate to the directory containing the Dockerfile
        docker build -t my-api-test .
